/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lokantaotomasyonu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Slymn
 */
public class GarsonPaneli extends javax.swing.JFrame {

    /**
     * Creates new form GarsonPaneli
     */
    public GarsonPaneli() {
       
      
        
        initComponents();
        
          cmbHesapAlmaMasaNo.removeAllItems();
        cmbHesapAlmaMasaNo.insertItemAt("Seçiniz...", 0);
        cmbHesapAlmaMasaNo.setSelectedIndex(0);
        
          ResultSet result;
        Connection connection = null;
        Statement statement ;
        
        int j = 1;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from siparisler ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
              
              cmbHesapAlmaMasaNo.insertItemAt("Masa "+result.getString("Masa_No"), j);
                j++;
         }

         jTable1.setModel(table);
         
         result=statement.executeQuery("Select * from paralar ");
         while(result.next()){
            lblPara.setText(result.getString("Garson")+" TL");
         }

        result.close();
        connection.close();
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbSiparisEkleMasaNo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbSiparisEkleTur = new javax.swing.JComboBox<>();
        cmbSiparisEkleUrun = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnSiparisEkle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbHesapAlmaMasaNo = new javax.swing.JComboBox<>();
        btnHesabıAl = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPara = new javax.swing.JLabel();
        btnBosalt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Garson Paneli");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Garson Paneli");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/close.png"))); // NOI18N
        jButton1.setText("Çıkış Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Sipariş Ekleme");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Masa No:");

        cmbSiparisEkleMasaNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Masa 1", "Masa 2", "Masa 3", "Masa 4", "Masa 5", "Masa 6", "Masa 7", "Masa 8", "Masa 9", "Masa 10", "Masa 11", "Masa 12", "Masa 13", "Masa 14", "Masa 15", "Masa 16", "Masa 17", "Masa 18", "Masa 19", "Masa 20" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Tür:");

        cmbSiparisEkleTur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Çorba", "Ana Yemek", "Tatlı", "İçecek", "Salata" }));
        cmbSiparisEkleTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSiparisEkleTurActionPerformed(evt);
            }
        });

        cmbSiparisEkleUrun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz..." }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Ürün:");

        btnSiparisEkle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiparisEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/signs.png"))); // NOI18N
        btnSiparisEkle.setText("Sipariş Ekle");
        btnSiparisEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiparisEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSiparisEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSiparisEkleTur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSiparisEkleUrun, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbSiparisEkleMasaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbSiparisEkleMasaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSiparisEkleTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSiparisEkleUrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnSiparisEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 255, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Hesap Alma");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Masa No:");

        cmbHesapAlmaMasaNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnHesabıAl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHesabıAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/interface.png"))); // NOI18N
        btnHesabıAl.setText("Hesabı Al");
        btnHesabıAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesabıAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHesabıAl, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbHesapAlmaMasaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbHesapAlmaMasaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHesabıAl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Toplam Alınan Para :");

        lblPara.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPara.setText("?");

        btnBosalt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBosalt.setText("Parayı Kasaya Boşalt");
        btnBosalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBosaltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBosalt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPara)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBosalt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Siparişler");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(302, 302, 302)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisPaneli().setVisible(true);
            }
        });
         GarsonPaneli.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSiparisEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiparisEkleActionPerformed
        // TODO add your handling code here:
        if(cmbSiparisEkleMasaNo.getSelectedIndex()==0||cmbSiparisEkleTur.getSelectedIndex()==0||cmbSiparisEkleUrun.getSelectedIndex()==0)JOptionPane.showMessageDialog(null, "Seçimlerinizi kontrol ediniz !");
        else{
            ResultSet result;
            Connection connection = null;
            Statement statement ;
            int varmi = 0;
            
            try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from lokantaotomasyon.siparisler WHERE Masa_No = "+cmbSiparisEkleMasaNo.getSelectedIndex()+"");
            
                String fiyat = "0";
                String durum= "";
                String siparis = "";
                String tfiyat = "0";
                
            while(result.next()){
                varmi++;
            }
            if(varmi==0){
                
                result=statement.executeQuery("SELECT * FROM lokantaotomasyon.menu where Adi ='"+cmbSiparisEkleUrun.getSelectedItem()+"'");
                while(result.next()){
                   fiyat = result.getString("Fiyati");
                }
                statement.executeUpdate("INSERT INTO `lokantaotomasyon`.`siparisler` (`Masa_No`, `Siparisler`, `Durum`, `Toplam_Fiyat`) VALUES ('"+cmbSiparisEkleMasaNo.getSelectedIndex()+"', '"+cmbSiparisEkleUrun.getSelectedItem()+"', 'Hazırlanıyor', '"+fiyat+"');");
                JOptionPane.showMessageDialog(null, "Sipariş alındı !");
                cmbHesapAlmaMasaNo.insertItemAt(cmbSiparisEkleMasaNo.getSelectedItem().toString(), cmbHesapAlmaMasaNo.getItemCount());
            }
            else{
                result=statement.executeQuery("Select * from lokantaotomasyon.siparisler WHERE Masa_No = "+cmbSiparisEkleMasaNo.getSelectedIndex()+"");
                while(result.next()){
                    durum = result.getString("Durum");
                    siparis = result.getString("Siparisler");
                    tfiyat = result.getString("Toplam_Fiyat");
                }
                if(durum.equals("Hazır")){
                    JOptionPane.showMessageDialog(null, "Önce hesabı almalısınız !");
                }
                else{
                    result=statement.executeQuery("SELECT * FROM lokantaotomasyon.menu where Adi ='"+cmbSiparisEkleUrun.getSelectedItem()+"'");
                    while(result.next()){
                    fiyat = result.getString("Fiyati");
                }
                    int fiyatint = Integer.parseInt(fiyat);
                    int tfiyatint = Integer.parseInt(tfiyat);
                    statement.executeUpdate("UPDATE `lokantaotomasyon`.`siparisler` SET `Siparisler`='"+(siparis+"+"+cmbSiparisEkleUrun.getSelectedItem())+"', `Toplam_Fiyat`='"+Integer.toString(tfiyatint+fiyatint)+"' WHERE `Masa_No`='"+cmbSiparisEkleMasaNo.getSelectedIndex()+"';");
                    JOptionPane.showMessageDialog(null, "Sipariş güncellendi !");
                }
            }
            result=statement.executeQuery("Select * from siparisler ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();
            
            

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
              
             
         }

         jTable1.setModel(table);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
        }
    }//GEN-LAST:event_btnSiparisEkleActionPerformed

    private void cmbSiparisEkleTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSiparisEkleTurActionPerformed
        // TODO add your handling code here:
        cmbSiparisEkleUrun.removeAllItems();
        cmbSiparisEkleUrun.insertItemAt("Seçiniz...", 0);
        cmbSiparisEkleUrun.setSelectedIndex(0);
        
        ResultSet result;
        Connection connection = null;
        Statement statement ;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from menu where Tur ='"+cmbSiparisEkleTur.getSelectedItem()+"'; ");
            int i=1;
            while(result.next()){
                cmbSiparisEkleUrun.insertItemAt(result.getString("Adi"), i);
                i++;
            }
            
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
    }
    }//GEN-LAST:event_cmbSiparisEkleTurActionPerformed

    private void btnHesabıAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesabıAlActionPerformed
        // TODO add your handling code here:
        
        if(cmbHesapAlmaMasaNo.getSelectedIndex()!=0){
        ResultSet result;
        Connection connection = null;
        Statement statement ;
        
                String durum= "";
                String tfiyat = "0";
                String garsonpara = lblPara.getText().substring(0, (lblPara.getText().length()-3));
                
                int tfiyatint = 0;
                int garsonparaint = 0;
                int toplampara =0;
                
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            
            result=statement.executeQuery("Select * from lokantaotomasyon.siparisler WHERE Masa_No = "+cmbHesapAlmaMasaNo.getSelectedItem().toString().substring(5)+"");
                while(result.next()){
                    
                    durum = result.getString("Durum");
                    tfiyat = result.getString("Toplam_Fiyat");
                }
                if(durum.equals("Hazır")){
                    tfiyatint = Integer.parseInt(tfiyat);
                    garsonparaint = Integer.parseInt(garsonpara);
                    toplampara= tfiyatint + garsonparaint;
                    
                    lblPara.setText(Integer.toString(toplampara)+" TL");
                    
                    statement.executeUpdate("UPDATE `lokantaotomasyon`.`paralar` SET `Garson`='"+Integer.toString(toplampara)+"' WHERE `ID`='1';");
                    statement.executeUpdate("DELETE FROM `lokantaotomasyon`.`siparisler` WHERE `Masa_No`='"+cmbHesapAlmaMasaNo.getSelectedItem().toString().substring(5)+"';");
                    JOptionPane.showMessageDialog(null, "Masa "+cmbHesapAlmaMasaNo.getSelectedItem().toString().substring(5)+" hesabı alındı !");
                }
                else {JOptionPane.showMessageDialog(null, "Sipariş hazır değil !");}
                
                result=statement.executeQuery("Select * from siparisler ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();
            
            

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
        
        cmbHesapAlmaMasaNo.removeAllItems();
        cmbHesapAlmaMasaNo.insertItemAt("Seçiniz...", 0);
        cmbHesapAlmaMasaNo.setSelectedIndex(0);
      
            int j =1;
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
              
              cmbHesapAlmaMasaNo.insertItemAt("Masa "+result.getString("Masa_No"), j);
                j++;
         }

         jTable1.setModel(table);
        }
        catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
    }
        }
        else JOptionPane.showMessageDialog(null, "Girişlerinizi kontrol ediniz !");
    }//GEN-LAST:event_btnHesabıAlActionPerformed

    private void btnBosaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBosaltActionPerformed
        // TODO add your handling code here:
        String toplampara =lblPara.getText().substring(0, lblPara.getText().length()-3);
        lblPara.setText("0 TL");
        String kasapara ="";
        ResultSet result;
        Connection connection = null;
        Statement statement ;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("select * from paralar");
            while(result.next()){
                kasapara = result.getString("Kasa");
            }
            
            int kasaparaint = Integer.parseInt(kasapara);
            int toplamparaint = Integer.parseInt(toplampara);
            int kasa = kasaparaint + toplamparaint;
            
            statement.executeUpdate("UPDATE `lokantaotomasyon`.`paralar` SET `Kasa`='"+Integer.toString(kasa)+"' WHERE `ID`='1';");
            statement.executeUpdate("UPDATE `lokantaotomasyon`.`paralar` SET `Garson`='0' WHERE `ID`='1';");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
        }
    }//GEN-LAST:event_btnBosaltActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        cmbHesapAlmaMasaNo.setSelectedIndex(jTable1.getSelectedRow()+1);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GarsonPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GarsonPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GarsonPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GarsonPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GarsonPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBosalt;
    private javax.swing.JButton btnHesabıAl;
    private javax.swing.JButton btnSiparisEkle;
    private javax.swing.JComboBox<String> cmbHesapAlmaMasaNo;
    private javax.swing.JComboBox<String> cmbSiparisEkleMasaNo;
    private javax.swing.JComboBox<String> cmbSiparisEkleTur;
    private javax.swing.JComboBox<String> cmbSiparisEkleUrun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPara;
    // End of variables declaration//GEN-END:variables
}
