/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lokantaotomasyonu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MCEYLAN
 */
public class YoneticiPaneli extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiPaneli
     */
    public YoneticiPaneli() {
        initComponents();
         ResultSet result;
        Connection connection = null;
        Statement statement ;
        
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from menu ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }

         jTable1.setModel(table);
         
         result=statement.executeQuery("Select * from paralar ");
         while(result.next()){
            lblPara.setText(result.getString("Kasa")+" TL");
         }

        result.close();
        connection.close();
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUrunEkleID = new javax.swing.JTextField();
        cmbUrunEkleTur = new javax.swing.JComboBox<>();
        txtUrunEkleAdi = new javax.swing.JTextField();
        txtUrunEkleFiyati = new javax.swing.JTextField();
        btnUrunEkle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtFiyatGuncelleID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFiyatGuncelleFiyati = new javax.swing.JTextField();
        btnGuncelle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUrunSilID = new javax.swing.JTextField();
        btnUrunSil = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        cmbUrunlerTur = new javax.swing.JComboBox<>();
        btnListele = new javax.swing.JButton();
        btnTumunu = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtGirisBilgiKadi = new javax.swing.JTextField();
        txtGirisBilgiSifre = new javax.swing.JTextField();
        btnGarson = new javax.swing.JButton();
        btnMutfak = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblPara = new javax.swing.JLabel();
        btnParayiAl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Yönetici Paneli");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Yönetici Paneli");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Menüye Ürün Ekleme");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tür:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Adı:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Fiyatı:");

        txtUrunEkleID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrunEkleIDKeyTyped(evt);
            }
        });

        cmbUrunEkleTur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Çorba", "Ana Yemek", "Tatlı", "İçecek", "Salata" }));

        txtUrunEkleAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrunEkleAdiKeyTyped(evt);
            }
        });

        txtUrunEkleFiyati.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrunEkleFiyatiKeyTyped(evt);
            }
        });

        btnUrunEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/signs.png"))); // NOI18N
        btnUrunEkle.setText("Ürün Ekle");
        btnUrunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrunEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUrunEkleID)
                            .addComponent(txtUrunEkleFiyati, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUrunEkleAdi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUrunEkleTur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUrunEkle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtUrunEkleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbUrunEkleTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUrunEkleAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtUrunEkleFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUrunEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Fiyat Güncelleme");

        txtFiyatGuncelleID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiyatGuncelleIDKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Fiyatı:");

        txtFiyatGuncelleFiyati.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiyatGuncelleFiyatiKeyTyped(evt);
            }
        });

        btnGuncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/arrows-1.png"))); // NOI18N
        btnGuncelle.setText("Fiyat Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFiyatGuncelleFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFiyatGuncelleID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtFiyatGuncelleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtFiyatGuncelleFiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Ürün Silme");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("ID:");

        txtUrunSilID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUrunSilIDKeyTyped(evt);
            }
        });

        btnUrunSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/close.png"))); // NOI18N
        btnUrunSil.setText("Ürünü Sil");
        btnUrunSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrunSilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUrunSil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUrunSilID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtUrunSilID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUrunSil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Ürünler");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Tür:");

        cmbUrunlerTur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "Çorba", "Ana Yemek", "Tatlı", "İçecek", "Salata" }));

        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });

        btnTumunu.setText("Tümünü Göster");
        btnTumunu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTumunuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(16, 16, 16)
                        .addComponent(cmbUrunlerTur, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListele, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTumunu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(327, 327, 327))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbUrunlerTur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListele)
                    .addComponent(btnTumunu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Giriş Bilgileri Güncelleme");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Kullanıcı Adı:");
        jLabel15.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Şifre:");

        btnGarson.setText("Garson Giriş Bilgilerini Güncelle");
        btnGarson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGarsonActionPerformed(evt);
            }
        });

        btnMutfak.setText("Mutfak Giriş Bilgilerini Güncelle");
        btnMutfak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutfakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGirisBilgiKadi)
                    .addComponent(txtGirisBilgiSifre))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGarson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMutfak))
                .addGap(24, 24, 24))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtGirisBilgiKadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGarson))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtGirisBilgiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMutfak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnCikis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lokantaotomasyonu/ikon/close.png"))); // NOI18N
        btnCikis.setText("Çıkış Yap");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Kasadaki Para");

        lblPara.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPara.setText("?");

        btnParayiAl.setText("Parayı Al");
        btnParayiAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParayiAlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnParayiAl)
                            .addComponent(lblPara))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnParayiAl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(324, 324, 324)
                        .addComponent(btnCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        // TODO add your handling code here:
        YoneticiPaneli.this.dispose();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisPaneli().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_btnCikisActionPerformed

    private void btnUrunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrunEkleActionPerformed
        // TODO add your handling code here:
        if(txtUrunEkleID.getText().equals("")||txtUrunEkleAdi.getText().equals("")||txtUrunEkleFiyati.getText().equals("")||cmbUrunEkleTur.getSelectedIndex()==0)JOptionPane.showMessageDialog(null, "Girişlerinizi kontrol ediniz !");
        else{
             ResultSet result;
            Connection connection = null;
            Statement statement ;
            int aynimi = 0;
            int adiaynimi = 0;
            String adi="";
            try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from lokantaotomasyon.menu WHERE ID = "+txtUrunEkleID.getText()+"");
            
            
            while(result.next()){
                
                aynimi++;
            }
            
            result=statement.executeQuery("Select * from lokantaotomasyon.menu");
            while(result.next()){
                adi =result.getString("Adi");
                if(adi.equals(txtUrunEkleAdi.getText())){
                    adiaynimi++;
                }
            }
            if(aynimi==0){
                if(adiaynimi>0)JOptionPane.showMessageDialog(null, "Aynı adla ikinci ürün eklenemez !");
                else{
                    statement.executeUpdate("INSERT INTO `lokantaotomasyon`.`menu` (`ID`, `Tur`, `Adi`, `Fiyati`) VALUES ('"+txtUrunEkleID.getText()+"', '"+cmbUrunEkleTur.getSelectedItem()+"', '"+txtUrunEkleAdi.getText()+"', '"+txtUrunEkleFiyati.getText()+"');");
                JOptionPane.showMessageDialog(null, "Ürün başarıyla eklendi !");
                txtUrunEkleAdi.setText("");
                txtUrunEkleFiyati.setText("");
                txtUrunEkleID.setText("");
                cmbUrunEkleTur.setSelectedIndex(0);
                }
                
            }
            else JOptionPane.showMessageDialog(null, "Aynı ID ile ikinci ürün kaydedilemez !");
            
            result=statement.executeQuery("Select * from menu ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }

         jTable1.setModel(table);
            }
            
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
        }
    }//GEN-LAST:event_btnUrunEkleActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        // TODO add your handling code here:
        if(txtFiyatGuncelleID.getText().equals("")||txtFiyatGuncelleFiyati.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Girişler boş bırakılamaz !");
        }
        else{
            ResultSet result;
            Connection connection = null;
            Statement statement ;
            int aynimi = 0;
            
            try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from lokantaotomasyon.menu WHERE ID = "+txtFiyatGuncelleID.getText()+"");
            
            
            while(result.next()){
                aynimi++;
            }
            if(aynimi==0){
                JOptionPane.showMessageDialog(null, "Bu ID ye ait ürün yoktur !");
            }
            else{
                statement.executeUpdate("UPDATE `lokantaotomasyon`.`menu` SET `Fiyati`='"+txtFiyatGuncelleFiyati.getText()+"' WHERE `ID`='"+txtFiyatGuncelleID.getText()+"';");
                JOptionPane.showMessageDialog(null, "Fiyat güncellendi !");
                txtFiyatGuncelleFiyati.setText("");
                txtFiyatGuncelleID.setText("");
            }
            
            result=statement.executeQuery("Select * from menu ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }

         jTable1.setModel(table);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void btnUrunSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrunSilActionPerformed
        // TODO add your handling code here:
        if(txtUrunSilID.getText().equals(""))JOptionPane.showMessageDialog(null, "ID alanı boş bırakılmaz !");
        else{
            ResultSet result;
            Connection connection = null;
            Statement statement ;
            int aynimi = 0;
            
            try{
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from lokantaotomasyon.menu WHERE ID = "+txtUrunSilID.getText()+"");
            
            
            while(result.next()){
                aynimi++;
            }
            if(aynimi==0){
                JOptionPane.showMessageDialog(null, "Bu ID ye ait ürün yoktur !");
            }
            else{
                statement.executeUpdate("DELETE FROM `lokantaotomasyon`.`menu` WHERE `ID`='"+txtUrunSilID.getText()+"';");
                JOptionPane.showMessageDialog(null, "Ürün silindi !");
                txtUrunSilID.setText("");
            } 
            
            result=statement.executeQuery("Select * from menu ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }

         jTable1.setModel(table);
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
        }
    }//GEN-LAST:event_btnUrunSilActionPerformed

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        // TODO add your handling code here:
         ResultSet result;
        Connection connection = null;
        Statement statement ;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from menu where Tur ='"+cmbUrunlerTur.getSelectedItem()+"'; ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }

         jTable1.setModel(table);

        result.close();
        connection.close();
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
    }
    }//GEN-LAST:event_btnListeleActionPerformed

    private void btnTumunuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTumunuActionPerformed
        // TODO add your handling code here:
         ResultSet result;
        Connection connection = null;
        Statement statement ;
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
            statement=connection.createStatement();
            result=statement.executeQuery("Select * from menu ");
            
            int sutunSayisi ;

            sutunSayisi=result.getMetaData().getColumnCount();

            DefaultTableModel table=new DefaultTableModel();

       
        for(int i=1;i<=sutunSayisi;i++)
            table.addColumn(result.getMetaData().getColumnName(i));
      
       
         while(result.next()){
              Object[] row=new Object[sutunSayisi];
               for(int i=1;i<=sutunSayisi;i++)
                  row[i-1]=result.getObject(i);
              table.addRow(row);
         }

         jTable1.setModel(table);

        result.close();
        connection.close();
    }
    catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
    }
    }//GEN-LAST:event_btnTumunuActionPerformed

    private void btnGarsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGarsonActionPerformed
        // TODO add your handling code here:
        if(txtGirisBilgiKadi.getText().length()<4||txtGirisBilgiSifre.getText().length()<4)JOptionPane.showMessageDialog(null, "Kullanıcı adı ve şifre en az 4 haneli olmalıdır !");
        else{
            ResultSet result;
            Connection connection = null;
            Statement statement ;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
                statement=connection.createStatement();
                statement.executeUpdate("UPDATE `lokantaotomasyon`.`giris_bilgileri` SET `Kullanici_Adi`='"+txtGirisBilgiKadi.getText()+"', `Sifre`='"+txtGirisBilgiSifre.getText()+"' WHERE `ID`='1';");
                JOptionPane.showMessageDialog(null, "Garson giriş bilgileri güncellendi !");
                txtGirisBilgiKadi.setText("");
                txtGirisBilgiSifre.setText("");
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
        }
    }//GEN-LAST:event_btnGarsonActionPerformed

    private void btnMutfakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMutfakActionPerformed
        // TODO add your handling code here:
        if(txtGirisBilgiKadi.getText().length()<4||txtGirisBilgiSifre.getText().length()<4)JOptionPane.showMessageDialog(null, "Kullanıcı adı ve şifre en az 4 haneli olmalıdır !");
        else{
            
            Connection connection = null;
            Statement statement ;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
                statement=connection.createStatement();
                statement.executeUpdate("UPDATE `lokantaotomasyon`.`giris_bilgileri` SET `Kullanici_Adi`='"+txtGirisBilgiKadi.getText()+"', `Sifre`='"+txtGirisBilgiSifre.getText()+"' WHERE `ID`='2';");
                JOptionPane.showMessageDialog(null, "Mutfak giriş bilgileri güncellendi !");
                txtGirisBilgiKadi.setText("");
                txtGirisBilgiSifre.setText("");
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
        }
    }//GEN-LAST:event_btnMutfakActionPerformed

    private void btnParayiAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParayiAlActionPerformed
        // TODO add your handling code here:
            ResultSet result;
            Connection connection = null;
            Statement statement ;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                connection=DriverManager.getConnection("jdbc:mysql://localhost/lokantaotomasyon","root","1234");     
                statement=connection.createStatement();
                statement.executeUpdate("UPDATE `lokantaotomasyon`.`paralar` SET `Kasa`='0' WHERE `ID`='1';");
                lblPara.setText("0 TL");
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, "VeriTabani Baglanti Hatasi"); 
            }
    }//GEN-LAST:event_btnParayiAlActionPerformed

    private void txtUrunEkleIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrunEkleIDKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {
 
            evt.consume();
        }
    }//GEN-LAST:event_txtUrunEkleIDKeyTyped

    private void txtUrunEkleFiyatiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrunEkleFiyatiKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {
 
            evt.consume();
        }
    }//GEN-LAST:event_txtUrunEkleFiyatiKeyTyped

    private void txtFiyatGuncelleIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiyatGuncelleIDKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {
 
            evt.consume();
        }
    }//GEN-LAST:event_txtFiyatGuncelleIDKeyTyped

    private void txtFiyatGuncelleFiyatiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiyatGuncelleFiyatiKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {
 
            evt.consume();
        }
    }//GEN-LAST:event_txtFiyatGuncelleFiyatiKeyTyped

    private void txtUrunSilIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrunSilIDKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {
 
            evt.consume();
        }
    }//GEN-LAST:event_txtUrunSilIDKeyTyped

    private void txtUrunEkleAdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUrunEkleAdiKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < 'a') || (caracter > 'z')) && ((caracter != '\b') && (caracter != ' '))) {
 
            evt.consume();
        }
    }//GEN-LAST:event_txtUrunEkleAdiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoneticiPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YoneticiPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnGarson;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnListele;
    private javax.swing.JButton btnMutfak;
    private javax.swing.JButton btnParayiAl;
    private javax.swing.JButton btnTumunu;
    private javax.swing.JButton btnUrunEkle;
    private javax.swing.JButton btnUrunSil;
    private javax.swing.JComboBox<String> cmbUrunEkleTur;
    private javax.swing.JComboBox<String> cmbUrunlerTur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPara;
    private javax.swing.JTextField txtFiyatGuncelleFiyati;
    private javax.swing.JTextField txtFiyatGuncelleID;
    private javax.swing.JTextField txtGirisBilgiKadi;
    private javax.swing.JTextField txtGirisBilgiSifre;
    private javax.swing.JTextField txtUrunEkleAdi;
    private javax.swing.JTextField txtUrunEkleFiyati;
    private javax.swing.JTextField txtUrunEkleID;
    private javax.swing.JTextField txtUrunSilID;
    // End of variables declaration//GEN-END:variables
}
